# Nombre de la aplicación
spring.application.name=soporte-tecnico-api

# Configuración de conexión a PostgreSQL
# Cambia 'soporte_db', 'postgres' y 'tu_contraseña' por tus datos reales
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate/JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'update' creará las tablas automáticamente si no existen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true